# -*- coding: utf-8 -*-
"""ACL Audit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZeJ-83-6ZIqzRJkwe7lhz21oHUCFoZ3T
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
from datetime import datetime
import warnings
warnings.filterwarnings('ignore')

plt.rcParams['figure.figsize'] = (12, 5)
plt.rcParams['font.family'] = 'DejaVu Sans'
sns.set_style("whitegrid")
print("=" * 65)
print("  ACL-STYLE AUDIT DATA ANALYTICS — Global Superstore Dataset")
print("=" * 65)

df = pd.read_csv('Global_Superstore2.csv', encoding='latin1')

df['Order Date'] = pd.to_datetime(df['Order Date'], dayfirst=True, errors='coerce')
df['Ship Date']  = pd.to_datetime(df['Ship Date'],  dayfirst=True, errors='coerce')

print(f"\n✅ Dataset loaded successfully")
print(f"   Rows    : {len(df):,}")
print(f"   Columns : {len(df.columns)}")
print(f"   Period  : {df['Order Date'].min().date()} → {df['Order Date'].max().date()}")
print(f"\nColumns available:")
print([c for c in df.columns])

print("\n" + "=" * 65)
print("  STEP 1: DATA PROFILING")
print("  ACL Equivalent: STATISTICS command")
print("  Purpose: Understand the dataset before running audit tests")
print("=" * 65)

total_rows    = len(df)
total_orders  = df['Order ID'].nunique()
total_customers = df['Customer ID'].nunique()
total_products  = df['Product ID'].nunique()
date_range_days = (df['Order Date'].max() - df['Order Date'].min()).days

print(f"""
DATASET PROFILE
───────────────────────────────────────────────
  Total transaction rows  : {total_rows:>10,}
  Unique orders           : {total_orders:>10,}
  Unique customers        : {total_customers:>10,}
  Unique products         : {total_products:>10,}
  Date range (days)       : {date_range_days:>10,}
  Countries covered       : {df['Country'].nunique():>10,}

FINANCIAL SUMMARY (Sales column)
───────────────────────────────────────────────
  Total Sales             : $ {df['Sales'].sum():>13,.2f}
  Total Profit            : $ {df['Profit'].sum():>13,.2f}
  Average Order Value     : $ {df['Sales'].mean():>13,.2f}
  Minimum Sale            : $ {df['Sales'].min():>13,.2f}
  Maximum Sale            : $ {df['Sales'].max():>13,.2f}
""")

print("COMPLETENESS CHECK (Missing Values)")
print("───────────────────────────────────────────────")
nulls = df.isnull().sum()
null_cols = nulls[nulls > 0]
if len(null_cols) == 0:
    print("  ✅ No missing values found in any column")
else:
    for col, count in null_cols.items():
        pct = count / total_rows * 100
        print(f"  ⚠️  {col:<30} {count:>6,} missing  ({pct:.1f}%)")

print("\n" + "=" * 65)
print("  STEP 2: DUPLICATE DETECTION")
print("  ACL Equivalent: DUPLICATES command")
print("  Purpose: Find transactions recorded more than once (fraud/error risk)")
print("=" * 65)

exact_dupes = df[df.duplicated(keep=False)].copy()

# Test 2: Same Order ID + Product ID + Sales amount appearing more than once
key_dupes = df[df.duplicated(
    subset=['Order ID', 'Product ID', 'Sales', 'Quantity'],
    keep=False
)].copy()

# Test 3: Same customer ordering identical product on same date
suspicious_dupes = df[df.duplicated(
    subset=['Customer ID', 'Product ID', 'Order Date', 'Sales'],
    keep=False
)].copy()

print(f"""
DUPLICATE ANALYSIS RESULTS
───────────────────────────────────────────────
  Exact duplicate rows          : {len(exact_dupes):,}
  Key-field duplicates          : {len(key_dupes):,}
    (Order ID + Product ID + Sales + Quantity)
  Suspicious same-day duplicates: {len(suspicious_dupes):,}
    (Same Customer + Product + Date + Amount)
""")

if len(exact_dupes) > 0:
    print("  🔴 FINDING: Exact duplicate rows detected — AUDIT RISK")
    print(f"     These {len(exact_dupes)} rows may represent double-posted transactions")
    print("\n  Sample duplicate records:")
    print(exact_dupes[['Order ID','Customer Name','Product Name','Sales','Order Date']]
          .head(6).to_string(index=False))
else:
    print("  ✅ No exact duplicate rows found")

if len(suspicious_dupes) > 0:
    print(f"\n  🟡 FINDING: {len(suspicious_dupes)} suspicious same-day identical orders")
    print("     Recommend investigation — possible system error or intentional duplication")
    print("\n  Sample suspicious records:")
    print(suspicious_dupes[['Order ID','Customer Name','Product Name','Sales','Order Date']]
          .head(6).to_string(index=False))

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
categories = ['Total Rows', 'Unique Key Combinations']
values = [total_rows, total_rows - len(key_dupes)]
colors = ['#2E75B6', '#1F4E79']
axes[0].bar(categories, values, color=colors, edgecolor='white', linewidth=1.5)
axes[0].set_title('Duplicate Detection Results\n(ACL: DUPLICATES Command)',
                   fontsize=13, fontweight='bold', pad=15)
axes[0].set_ylabel('Number of Records')
for i, v in enumerate(values):
    axes[0].text(i, v + 50, f'{v:,}', ha='center', fontsize=11, fontweight='bold')

dupe_types = {
    'Clean Records': total_rows - len(exact_dupes) - len(suspicious_dupes),
    'Exact Duplicates': max(len(exact_dupes), 1),
    'Suspicious Same-Day': max(len(suspicious_dupes), 1)
}
wedge_colors = ['#1F4E79', '#FF6B6B', '#FFA07A']
axes[1].pie(dupe_types.values(), labels=dupe_types.keys(), colors=wedge_colors,
            autopct='%1.1f%%', startangle=90, textprops={'fontsize': 10})
axes[1].set_title('Record Classification\nby Duplicate Status',
                   fontsize=13, fontweight='bold', pad=15)
plt.tight_layout()
plt.savefig('audit_01_duplicates.png', dpi=150, bbox_inches='tight')
plt.show()
print("\n  📊 Chart saved: audit_01_duplicates.png")

print("\n" + "=" * 65)
print("  STEP 3: GAP DETECTION")
print("  ACL Equivalent: GAPS command")
print("  Purpose: Find missing numbers in sequences (missing invoices = fraud risk)")
print("=" * 65)

df['Order_Num'] = df['Order ID'].str.extract(r'-(\d+)$').astype(float)

# Find gaps in order number sequence
order_nums_sorted = df['Order_Num'].dropna().drop_duplicates().sort_values()
expected_seq = set(range(
    int(order_nums_sorted.min()),
    int(order_nums_sorted.max()) + 1
))
actual_seq = set(order_nums_sorted.astype(int))
gaps = sorted(expected_seq - actual_seq)

total_expected = len(expected_seq)
total_found = len(actual_seq)
total_gaps = len(gaps)
gap_pct = total_gaps / total_expected * 100

print(f"""
GAP ANALYSIS RESULTS
───────────────────────────────────────────────
  Order number range     : {int(order_nums_sorted.min()):,} → {int(order_nums_sorted.max()):,}
  Expected count         : {total_expected:>8,}
  Actual unique orders   : {total_found:>8,}
  GAPS FOUND             : {total_gaps:>8,}  ({gap_pct:.1f}% missing)
""")

if total_gaps == 0:
    print("  ✅ No gaps in order number sequence — sequence is complete")
elif gap_pct < 5:
    print(f"  🟡 LOW RISK: {total_gaps:,} gaps ({gap_pct:.1f}%) — within acceptable range")
    print(f"     First 10 missing order numbers: {gaps[:10]}")
elif gap_pct < 15:
    print(f"  🟠 MEDIUM RISK: {total_gaps:,} gaps ({gap_pct:.1f}%) — recommend investigation")
    print(f"     Could indicate cancelled orders, deleted records, or system errors")
    print(f"     First 10 missing order numbers: {gaps[:10]}")
else:
    print(f"  🔴 HIGH RISK: {total_gaps:,} gaps ({gap_pct:.1f}%) — significant sequence breaks")
    print(f"     HIGH AUDIT RISK — missing sequences may indicate deleted transactions")

# Visualise gaps over time
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Orders by year
orders_by_year = df.groupby(df['Order Date'].dt.year)['Order ID'].nunique()
axes[0].bar(orders_by_year.index.astype(str), orders_by_year.values,
            color='#2E75B6', edgecolor='white', linewidth=1.5)
axes[0].set_title('Orders Per Year\n(Completeness Check)',
                   fontsize=13, fontweight='bold', pad=15)
axes[0].set_ylabel('Number of Unique Orders')
axes[0].set_xlabel('Year')
for i, v in enumerate(orders_by_year.values):
    axes[0].text(i, v + 5, str(v), ha='center', fontsize=10, fontweight='bold')

# Sequence summary
seq_data = ['Expected in Sequence', 'Actual Found', 'Gaps / Missing']
seq_vals  = [total_expected, total_found, total_gaps]
seq_colors = ['#1F4E79', '#2E75B6', '#FF6B6B']
bars = axes[1].bar(seq_data, seq_vals, color=seq_colors, edgecolor='white', linewidth=1.5)
axes[1].set_title('Gap Detection Results\n(ACL: GAPS Command)',
                   fontsize=13, fontweight='bold', pad=15)
axes[1].set_ylabel('Count')
for bar, v in zip(bars, seq_vals):
    axes[1].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 10,
                 f'{v:,}', ha='center', fontsize=10, fontweight='bold')
plt.tight_layout()
plt.savefig('audit_02_gaps.png', dpi=150, bbox_inches='tight')
plt.show()
print("  📊 Chart saved: audit_02_gaps.png")

print("\n" + "=" * 65)
print("  STEP 4: STRATIFICATION")
print("  ACL Equivalent: STRATIFY command")
print("  Purpose: Group transactions by value bands — reveals unusual concentrations")
print("=" * 65)

# Define value bands (common in audit — focus on high-value transactions)
bins   = [0, 100, 500, 1000, 2500, 5000, float('inf')]
labels = ['<$100', '$100–500', '$500–1K', '$1K–2.5K', '$2.5K–5K', '>$5K']

df['Sales_Band'] = pd.cut(df['Sales'], bins=bins, labels=labels, right=True)
strat = df.groupby('Sales_Band', observed=False).agg(
    Count=('Sales', 'count'),
    Total_Sales=('Sales', 'sum'),
    Avg_Sale=('Sales', 'mean'),
    Min_Sale=('Sales', 'min'),
    Max_Sale=('Sales', 'max')
).reset_index()
strat['% of Records'] = (strat['Count'] / len(df) * 100).round(1)
strat['% of Value']   = (strat['Total_Sales'] / df['Sales'].sum() * 100).round(1)

print("\nSTRATIFICATION TABLE")
print("─" * 75)
print(f"{'Band':<12} {'Count':>8} {'% Recs':>8} {'Total $':>14} {'% Value':>9} {'Avg $':>10}")
print("─" * 75)
for _, r in strat.iterrows():
    print(f"{str(r['Sales_Band']):<12} {r['Count']:>8,} {r['% of Records']:>7.1f}% "
          f"{r['Total_Sales']:>13,.0f} {r['% of Value']:>8.1f}% {r['Avg_Sale']:>9,.0f}")
print("─" * 75)

# Commented out IPython magic to ensure Python compatibility.
# High-value focus (audit always focuses on >$5K — highest risk)
high_value = df[df['Sales'] > 5000].copy()
print(f"""
HIGH-VALUE TRANSACTIONS FOCUS (>$5,000)
───────────────────────────────────────────────
  Count              : {len(high_value):,} transactions
#   % of all records   : {len(high_value)/len(df)*100:.1f}%
  Total value        : $ {high_value['Sales'].sum():,.2f}
#   % of total sales   : {high_value['Sales'].sum()/df['Sales'].sum()*100:.1f}%
  Highest single sale: $ {high_value['Sales'].max():,.2f}

  ⚠️  AUDIT FOCUS: High-value transactions represent disproportionate
     value — these should be prioritised for detailed testing
""")

# Stratification visualisation
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Count by band
colors_strat = ['#D6E4F0','#A9CCE3','#7FB3D3','#5499C9','#2E75B6','#1F4E79']
axes[0].bar(strat['Sales_Band'].astype(str), strat['Count'],
            color=colors_strat, edgecolor='white', linewidth=1.2)
axes[0].set_title('Transaction Count by Value Band\n(ACL: STRATIFY Command)',
                   fontsize=13, fontweight='bold', pad=15)
axes[0].set_xlabel('Sales Value Band')
axes[0].set_ylabel('Number of Transactions')
axes[0].tick_params(axis='x', rotation=20)
for i, v in enumerate(strat['Count']):
    axes[0].text(i, v + 20, f'{v:,}', ha='center', fontsize=9, fontweight='bold')

# Value concentration
axes[1].bar(strat['Sales_Band'].astype(str), strat['% of Value'],
            color=colors_strat, edgecolor='white', linewidth=1.2)
axes[1].set_title('Value Concentration by Band\n(% of Total Sales)',
                   fontsize=13, fontweight='bold', pad=15)
axes[1].set_xlabel('Sales Value Band')
axes[1].set_ylabel('% of Total Sales Value')
axes[1].tick_params(axis='x', rotation=20)
for i, v in enumerate(strat['% of Value']):
    axes[1].text(i, v + 0.3, f'{v:.1f}%', ha='center', fontsize=9, fontweight='bold')

plt.tight_layout()
plt.savefig('audit_03_stratification.png', dpi=150, bbox_inches='tight')
plt.show()
print("  📊 Chart saved: audit_03_stratification.png")

print("\n" + "=" * 65)
print("  STEP 5: OUTLIER DETECTION")
print("  ACL Equivalent: STATISTICS + FILTER commands")
print("  Purpose: Find statistically unusual transactions")
print("=" * 65)

mean_s  = df['Sales'].mean()
std_s   = df['Sales'].std()
mean_p  = df['Profit'].mean()
std_p   = df['Profit'].std()

# Standard outliers (> mean + 3 standard deviations)
sales_outliers  = df[df['Sales']  > mean_s  + 3*std_s].copy()
profit_outliers = df[df['Profit'] > mean_p  + 3*std_p].copy()

# Negative profit on high sales (loss-making high-value deals — suspicious)
loss_high_sales = df[(df['Profit'] < 0) & (df['Sales'] > 1000)].copy()

# Extreme discounts (>70% discount — possible fraud or pricing error)
if 'Discount' in df.columns:
    extreme_discount = df[df['Discount'] >= 0.7].copy()
else:
    extreme_discount = pd.DataFrame()

print(f"""
OUTLIER ANALYSIS RESULTS
───────────────────────────────────────────────
  Sales statistics:
    Mean     : $ {mean_s:>10,.2f}
    Std Dev  : $ {std_s:>10,.2f}
    Threshold: $ {mean_s + 3*std_s:>10,.2f}  (mean + 3σ)

  Sales outliers  (>3σ above mean)  : {len(sales_outliers):>6,} transactions  🔴
  Profit outliers (>3σ above mean)  : {len(profit_outliers):>6,} transactions
  High-sales LOSS transactions      : {len(loss_high_sales):>6,} transactions  🔴
  Extreme discounts (≥70%)          : {len(extreme_discount):>6,} transactions  🟠
""")

if len(sales_outliers) > 0:
    print("  TOP 5 HIGHEST-VALUE OUTLIER TRANSACTIONS:")
    print("  " + "─" * 60)
    top_outliers = sales_outliers.nlargest(5, 'Sales')
    for _, r in top_outliers.iterrows():
        print(f"  Order {r['Order ID']} | {str(r['Order Date'].date())} | "
              f"${r['Sales']:>10,.2f} | {r['Customer Name']}")

if len(loss_high_sales) > 0:
    print(f"\n  🔴 FINDING: {len(loss_high_sales)} high-value transactions recorded at a LOSS")
    print("     These require investigation — possible pricing errors or intentional discounting")
    print("\n  Sample loss-making high-value transactions:")
    sample = loss_high_sales.nsmallest(5, 'Profit')
    for _, r in sample.iterrows():
        print(f"  {r['Order ID']} | ${r['Sales']:>8,.0f} sales | "
              f"${r['Profit']:>8,.0f} profit | {r['Sub-Category']}")

if len(extreme_discount) > 0:
    print(f"\n  🟠 FINDING: {len(extreme_discount)} transactions with ≥70% discount")
    print("     Extreme discounts are a known fraud risk — authorisation trail required")

# Outlier visualisation
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Sales distribution with outlier threshold
axes[0].hist(df['Sales'], bins=80, color='#2E75B6', edgecolor='white', alpha=0.8)
threshold = mean_s + 3*std_s
axes[0].axvline(threshold, color='#FF4444', linewidth=2.5, linestyle='--',
                label=f'Outlier threshold: ${threshold:,.0f}')
axes[0].axvline(mean_s, color='#1F4E79', linewidth=2, linestyle='-',
                label=f'Mean: ${mean_s:,.0f}')
axes[0].set_title('Sales Distribution with Outlier Threshold\n(ACL: STATISTICS + FILTER)',
                   fontsize=12, fontweight='bold', pad=15)
axes[0].set_xlabel('Sales Value ($)')
axes[0].set_ylabel('Frequency')
axes[0].legend(fontsize=9)
axes[0].set_xlim(0, df['Sales'].quantile(0.99))

# Profit vs Sales scatter (highlight loss-making)
sample_n = min(3000, len(df))
sample_df = df.sample(n=sample_n, random_state=42)
colors_scatter = ['#FF4444' if p < 0 else '#2E75B6' for p in sample_df['Profit']]
axes[1].scatter(sample_df['Sales'], sample_df['Profit'],
                c=colors_scatter, alpha=0.4, s=15)
axes[1].axhline(0, color='black', linewidth=1.5, linestyle='-')
axes[1].set_title('Sales vs Profit — Loss Detection\n(Red = Loss-making transactions)',
                   fontsize=12, fontweight='bold', pad=15)
axes[1].set_xlabel('Sales Value ($)')
axes[1].set_ylabel('Profit ($)')
red_patch = mpatches.Patch(color='#FF4444', label='Loss (Profit < 0)')
blue_patch = mpatches.Patch(color='#2E75B6', label='Profitable')
axes[1].legend(handles=[blue_patch, red_patch], fontsize=9)

plt.tight_layout()
plt.savefig('audit_04_outliers.png', dpi=150, bbox_inches='tight')
plt.show()
print("  📊 Chart saved: audit_04_outliers.png")

print("\n" + "=" * 65)
print("  STEP 6: BENFORD'S LAW TEST")
print("  ACL Equivalent: BENFORD command")
print("  Purpose: Detect fabricated or manipulated financial figures")
print("=" * 65)
print("""
  WHAT IS BENFORD'S LAW?
  ─────────────────────────────────────────────────────────
  In genuine financial datasets, the FIRST DIGIT of amounts
  follows a predictable mathematical distribution:
    1 appears first ~30.1% of the time
    2 appears first ~17.6% of the time
    9 appears first  ~4.6% of the time

  If someone fabricates or manipulates numbers, they tend to
  use digits too evenly — deviating from Benford's Law.
  This is one of the most powerful fraud detection techniques
  used by auditors worldwide.
""")

# Calculate Benford's expected distribution
benford_expected = {d: np.log10(1 + 1/d) * 100 for d in range(1, 10)}

# Get first digits of sales amounts (only positive, >0)
sales_positive = df[df['Sales'] > 0]['Sales']
first_digits = sales_positive.astype(str).str.replace('.', '').str.lstrip('0').str[0]
first_digits = first_digits[first_digits.str.isdigit()].astype(int)
first_digits = first_digits[first_digits.between(1, 9)]

observed_counts = first_digits.value_counts().sort_index()
observed_pct    = (observed_counts / len(first_digits) * 100)

print("BENFORD'S LAW ANALYSIS — Sales Amounts")
print("─" * 58)
print(f"{'Digit':>6} {'Expected %':>12} {'Observed %':>12} {'Deviation':>12} {'Flag':>8}")
print("─" * 58)
deviation_flags = []
for d in range(1, 10):
    exp  = benford_expected[d]
    obs  = observed_pct.get(d, 0)
    dev  = obs - exp
    flag = "🔴 HIGH" if abs(dev) > 3 else ("🟡 MED" if abs(dev) > 1.5 else "✅ OK")
    if abs(dev) > 3:
        deviation_flags.append((d, exp, obs, dev))
    print(f"  {d:>4}   {exp:>10.1f}%  {obs:>10.1f}%  {dev:>+10.1f}%  {flag:>10}")
print("─" * 58)

if deviation_flags:
    print(f"\n  🔴 FINDING: {len(deviation_flags)} digit(s) deviate significantly from Benford's Law")
    for d, exp, obs, dev in deviation_flags:
        direction = "over-represented" if dev > 0 else "under-represented"
        print(f"     Digit {d}: expected {exp:.1f}%, found {obs:.1f}% — {direction}")
    print("\n  ⚠️  Significant deviations from Benford's Law may indicate:")
    print("     • Fabricated or rounded transaction amounts")
    print("     • Data entry errors or system rounding")
    print("     • Legitimate but unusual business pattern (require further review)")
else:
    print("\n  ✅ Sales amounts broadly conform to Benford's Law")
    print("     No significant manipulation signals detected")

# Benford visualisation
fig, ax = plt.subplots(figsize=(13, 6))
x = np.arange(1, 10)
width = 0.38
bars1 = ax.bar(x - width/2,
               [benford_expected[d] for d in range(1,10)],
               width, label="Benford's Expected", color='#1F4E79',
               edgecolor='white', linewidth=1.2, alpha=0.9)
bars2 = ax.bar(x + width/2,
               [observed_pct.get(d, 0) for d in range(1,10)],
               width, label='Observed (Dataset)', color='#2E75B6',
               edgecolor='white', linewidth=1.2, alpha=0.85)

# Highlight significant deviations
for d, _, _, _ in deviation_flags:
    ax.bar(d + width/2, observed_pct.get(d, 0), width,
           color='#FF4444', edgecolor='white', linewidth=1.2, alpha=0.9)

ax.set_xticks(x)
ax.set_xticklabels([f'Digit {d}' for d in range(1,10)], fontsize=10)
ax.set_xlabel('First Digit', fontsize=11, fontweight='bold')
ax.set_ylabel('Frequency (%)', fontsize=11, fontweight='bold')
ax.set_title("Benford's Law Analysis — Sales Amounts\n"
             "(ACL: BENFORD command | Red bars = significant deviation)",
             fontsize=13, fontweight='bold', pad=15)
ax.legend(fontsize=11)
ax.set_ylim(0, max(max(benford_expected.values()),
                   observed_pct.max() if len(observed_pct) > 0 else 35) * 1.2)
plt.tight_layout()
plt.savefig('audit_05_benfords_law.png', dpi=150, bbox_inches='tight')
plt.show()
print("  📊 Chart saved: audit_05_benfords_law.png")

print("\n" + "=" * 65)
print("  STEP 7: UNUSUAL TIMING ANALYSIS")
print("  ACL Equivalent: FILTER command on date/time fields")
print("  Purpose: Detect transactions outside normal business patterns")
print("=" * 65)

# Weekend orders
df['Day_of_Week'] = df['Order Date'].dt.day_name()
df['Is_Weekend']  = df['Order Date'].dt.dayofweek >= 5  # 5=Sat, 6=Sun
weekend_orders    = df[df['Is_Weekend']].copy()

# Year-end transactions (last 5 days of December — classic audit risk)
df['Month']       = df['Order Date'].dt.month
df['Day']         = df['Order Date'].dt.day
year_end          = df[(df['Month'] == 12) & (df['Day'] >= 27)].copy()

# Unusually fast shipping (same-day or next-day — possible backdating)
df['Ship_Lag_Days'] = (df['Ship Date'] - df['Order Date']).dt.days
same_day_ship     = df[df['Ship_Lag_Days'] == 0].copy()
negative_lag      = df[df['Ship_Lag_Days'] < 0].copy()

print(f"""
TIMING ANALYSIS RESULTS
───────────────────────────────────────────────
  Weekend orders (Sat/Sun)        : {len(weekend_orders):>7,}  ({len(weekend_orders)/len(df)*100:.1f}% of all orders)
  Year-end orders (Dec 27–31)     : {len(year_end):>7,}
  Same-day shipped orders         : {len(same_day_ship):>7,}
  Negative shipping lag (error?)  : {len(negative_lag):>7,}

  Average shipping lag (days)     : {df['Ship_Lag_Days'].mean():>7.1f}
  Max shipping lag (days)         : {df['Ship_Lag_Days'].max():>7.0f}
""")

if len(weekend_orders) / len(df) > 0.25:
    print("  🟡 FINDING: >25% of orders placed on weekends")
    print("     In a B2B context this may be unusual — verify business model")

if len(year_end) > 0:
    print(f"  🟡 FINDING: {len(year_end)} transactions in last 5 days of December")
    print("     Year-end transactions are a classic audit focus area")
    print("     Revenue recognition and cut-off testing recommended")
    print(f"     Total value of year-end transactions: ${year_end['Sales'].sum():,.2f}")

if len(negative_lag) > 0:
    print(f"\n  🔴 FINDING: {len(negative_lag)} records where Ship Date < Order Date")
    print("     DATA QUALITY ERROR — shipment cannot precede order")
    print("     Indicates date entry errors or possible backdating")

# Orders by day of week
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
day_order = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']
day_counts = df['Day_of_Week'].value_counts().reindex(day_order, fill_value=0)
bar_colors = ['#2E75B6']*5 + ['#FF6B6B']*2
axes[0].bar(range(7), day_counts.values, color=bar_colors, edgecolor='white', linewidth=1.2)
axes[0].set_xticks(range(7))
axes[0].set_xticklabels(['Mon','Tue','Wed','Thu','Fri','Sat','Sun'], fontsize=10)
axes[0].set_title('Orders by Day of Week\n(Red = Weekend — Unusual Timing Flag)',
                   fontsize=12, fontweight='bold', pad=15)
axes[0].set_ylabel('Number of Orders')
for i, v in enumerate(day_counts.values):
    axes[0].text(i, v + 5, str(v), ha='center', fontsize=9, fontweight='bold')

# Shipping lag distribution
lag_data = df[df['Ship_Lag_Days'].between(0, 14)]['Ship_Lag_Days']
axes[1].hist(lag_data, bins=15, color='#2E75B6', edgecolor='white', linewidth=1.2)
axes[1].axvline(lag_data.mean(), color='#FF4444', linewidth=2.5, linestyle='--',
                label=f'Mean: {lag_data.mean():.1f} days')
axes[1].set_title('Shipping Lag Distribution\n(Same-day shipping = potential backdating risk)',
                   fontsize=12, fontweight='bold', pad=15)
axes[1].set_xlabel('Days Between Order and Shipment')
axes[1].set_ylabel('Frequency')
axes[1].legend(fontsize=10)
plt.tight_layout()
plt.savefig('audit_06_timing.png', dpi=150, bbox_inches='tight')
plt.show()
print("  📊 Chart saved: audit_06_timing.png")

print("\n" + "=" * 65)
print("  STEP 8: THREE-WAY MATCHING & CROSS-FIELD VALIDATION")
print("  ACL Equivalent: JOIN command + FILTER")
print("  Purpose: Verify internal consistency across related data fields")
print("=" * 65)

# Profit margin consistency check
df['Calculated_Margin'] = (df['Profit'] / df['Sales'] * 100).round(2)
extreme_margin  = df[df['Calculated_Margin'] < -50].copy()   # >50% loss
unusual_margin  = df[(df['Calculated_Margin'] > 100)].copy() # >100% margin impossible

# Quantity vs Sales validation (unit price consistency)
df['Unit_Price'] = df['Sales'] / df['Quantity']
avg_unit = df.groupby('Product ID')['Unit_Price'].mean()
df['Expected_Price'] = df['Product ID'].map(avg_unit)
df['Price_Deviation_Pct'] = abs(df['Unit_Price'] - df['Expected_Price']) / df['Expected_Price'] * 100
price_anomalies = df[df['Price_Deviation_Pct'] > 50].copy()

print(f"""
CROSS-FIELD VALIDATION RESULTS
───────────────────────────────────────────────
  Transactions with >50% loss margin   : {len(extreme_margin):>7,}  🔴
  Transactions with impossible margin  : {len(unusual_margin):>7,}
  Price deviations >50% from average   : {len(price_anomalies):>7,}  🟠

  Overall dataset margin:
    Mean profit margin  : {df['Calculated_Margin'].mean():>7.1f}%
    Median margin       : {df['Calculated_Margin'].median():>7.1f}%
""")

if len(extreme_margin) > 0:
    print(f"  🔴 FINDING: {len(extreme_margin)} transactions with >50% loss")
    top_losses = extreme_margin.nsmallest(5, 'Calculated_Margin')
    for _, r in top_losses.iterrows():
        print(f"     {r['Order ID']} | ${r['Sales']:>8,.0f} sale | "
              f"${r['Profit']:>8,.0f} profit | {r['Calculated_Margin']:>6.0f}% margin")

if len(price_anomalies) > 0:
    print(f"\n  🟠 FINDING: {len(price_anomalies)} records with unit price >50% from product average")
    print("     Possible causes: unauthorised discounts, data entry errors, product variants")

# Margin by category
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

margin_by_cat = df.groupby('Category')['Calculated_Margin'].mean()
colors_cat = ['#1F4E79','#2E75B6','#5499C9']
axes[0].bar(margin_by_cat.index, margin_by_cat.values, color=colors_cat,
            edgecolor='white', linewidth=1.5)
axes[0].axhline(0, color='red', linewidth=1.5, linestyle='--')
axes[0].set_title('Average Profit Margin by Category\n(ACL: Three-Way Matching)',
                   fontsize=12, fontweight='bold', pad=15)
axes[0].set_ylabel('Average Profit Margin (%)')
for i, (cat, v) in enumerate(margin_by_cat.items()):
    axes[0].text(i, v + 0.5, f'{v:.1f}%', ha='center', fontsize=11, fontweight='bold')

# Sub-category margin heatmap
subcat_margin = df.groupby('Sub-Category')['Calculated_Margin'].mean().sort_values()
colors_sub = ['#FF4444' if v < 0 else '#2E75B6' for v in subcat_margin.values]
axes[1].barh(subcat_margin.index, subcat_margin.values, color=colors_sub,
             edgecolor='white', linewidth=0.8)
axes[1].axvline(0, color='black', linewidth=1.5)
axes[1].set_title('Profit Margin by Sub-Category\n(Red = Loss-making categories)',
                   fontsize=12, fontweight='bold', pad=15)
axes[1].set_xlabel('Average Profit Margin (%)')
plt.tight_layout()
plt.savefig('audit_07_matching.png', dpi=150, bbox_inches='tight')
plt.show()
print("  📊 Chart saved: audit_07_matching.png")

print("\n" + "=" * 65)
print("  STEP 9: AGED ANALYSIS — Shipping Performance")
print("  ACL Equivalent: AGE command")
print("  Purpose: Identify delayed or aged transactions requiring follow-up")
print("=" * 65)

# Age shipping lag into bands
age_bins   = [-1, 0, 3, 7, 14, 30, float('inf')]
age_labels = ['Same Day', '1–3 Days', '4–7 Days', '8–14 Days', '15–30 Days', '>30 Days']
df['Shipping_Age_Band'] = pd.cut(df['Ship_Lag_Days'], bins=age_bins, labels=age_labels)

aged = df.groupby('Shipping_Age_Band', observed=False).agg(
    Count=('Order ID','count'),
    Total_Sales=('Sales','sum')
).reset_index()
aged['% Count'] = (aged['Count'] / len(df) * 100).round(1)
aged['% Value'] = (aged['Total_Sales'] / df['Sales'].sum() * 100).round(1)

print("\nSHIPPING AGE ANALYSIS TABLE")
print("─" * 65)
print(f"{'Age Band':<14} {'Count':>8} {'% Records':>11} {'Total Value':>14} {'% Value':>10}")
print("─" * 65)
for _, r in aged.iterrows():
    risk = "  🔴" if str(r['Shipping_Age_Band']) in ['>30 Days','15–30 Days'] else ""
    print(f"{str(r['Shipping_Age_Band']):<14} {r['Count']:>8,} {r['% Count']:>10.1f}%"
          f" {r['Total_Sales']:>13,.0f} {r['% Value']:>9.1f}%{risk}")

overdue = df[df['Ship_Lag_Days'] > 14]
print(f"""
  AUDIT RISK ITEMS
  ───────────────────────────────────────────────
  Orders taking >14 days to ship: {len(overdue):,}
  Value at risk (>14 day orders): ${overdue['Sales'].sum():,.2f}

  {"🔴 HIGH RISK: Significant value in aged shipping band" if overdue['Sales'].sum() > 50000 else "✅ Shipping performance within acceptable range"}
""")

# Aged analysis chart
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
age_colors = ['#1F4E79','#2E75B6','#5499C9','#FFA07A','#FF6B6B','#FF0000']
axes[0].bar(aged['Shipping_Age_Band'].astype(str), aged['Count'],
            color=age_colors, edgecolor='white', linewidth=1.2)
axes[0].set_title('Order Age Analysis — Shipping Lag\n(ACL: AGE Command)',
                   fontsize=12, fontweight='bold', pad=15)
axes[0].set_xlabel('Shipping Age Band')
axes[0].set_ylabel('Number of Orders')
axes[0].tick_params(axis='x', rotation=20)

axes[1].bar(aged['Shipping_Age_Band'].astype(str), aged['% Value'],
            color=age_colors, edgecolor='white', linewidth=1.2)
axes[1].set_title('% of Total Sales Value by Shipping Age\n(Red = High-risk aged transactions)',
                   fontsize=12, fontweight='bold', pad=15)
axes[1].set_xlabel('Shipping Age Band')
axes[1].set_ylabel('% of Total Sales')
axes[1].tick_params(axis='x', rotation=20)
plt.tight_layout()
plt.savefig('audit_08_aged.png', dpi=150, bbox_inches='tight')
plt.show()
print("  📊 Chart saved: audit_08_aged.png")

print("\n" + "=" * 65)
print("  AUDIT FINDINGS SUMMARY REPORT")
print("  Prepared by: Mohamed Faris Abdurrahman")
print("  Date       :", datetime.now().strftime("%d %B %Y"))
print("=" * 65)

findings = []

# Collect all findings
if len(exact_dupes) > 0:
    findings.append(("🔴 HIGH",   "Duplicate Detection",
                     f"{len(exact_dupes)} exact duplicate rows detected — possible double-posting",
                     "Remove duplicates; investigate source system controls"))

if len(suspicious_dupes) > 0:
    findings.append(("🟡 MEDIUM", "Duplicate Detection",
                     f"{len(suspicious_dupes)} same-day identical customer-product-amount records",
                     "Verify with business — could be legitimate repeat orders or system error"))

if total_gaps > 0 and gap_pct > 5:
    findings.append(("🟠 MEDIUM", "Gap Detection",
                     f"{total_gaps:,} gaps ({gap_pct:.1f}%) in order number sequence",
                     "Obtain explanation for missing order numbers from management"))

findings.append(("🟡 MEDIUM", "Stratification",
                 f"Top value band (>$5K) represents {high_value['Sales'].sum()/df['Sales'].sum()*100:.1f}% of total sales "
                 f"in only {len(high_value)/len(df)*100:.1f}% of transactions",
                 "Apply 100% audit coverage to all transactions >$5,000"))

if len(sales_outliers) > 0:
    findings.append(("🔴 HIGH",   "Outlier Detection",
                     f"{len(sales_outliers)} transactions exceed 3-sigma threshold (>${mean_s+3*std_s:,.0f})",
                     "Obtain supporting documentation for all outlier transactions"))

if len(loss_high_sales) > 0:
    findings.append(("🔴 HIGH",   "Loss Transactions",
                     f"{len(loss_high_sales)} high-value transactions (>$1,000) recorded at a loss",
                     "Review authorisation trail; verify pricing and discount approvals"))

if len(extreme_discount) > 0:
    findings.append(("🟠 MEDIUM", "Extreme Discounts",
                     f"{len(extreme_discount)} transactions with ≥70% discount",
                     "Verify management approval for all extreme discounts"))

if deviation_flags:
    findings.append(("🟡 MEDIUM", "Benford's Law",
                     f"{len(deviation_flags)} digit(s) deviate significantly from expected distribution",
                     "Investigate whether amounts are being rounded or fabricated"))

if len(year_end) > 0:
    findings.append(("🟡 MEDIUM", "Year-End Cut-off",
                     f"{len(year_end)} transactions in last 5 days of December (${year_end['Sales'].sum():,.0f})",
                     "Perform revenue recognition cut-off testing on year-end transactions"))

if len(negative_lag) > 0:
    findings.append(("🔴 HIGH",   "Data Integrity",
                     f"{len(negative_lag)} records where Ship Date precedes Order Date",
                     "Correct data entry errors; review system date validation controls"))

print(f"\n  TOTAL FINDINGS: {len(findings)}")
print(f"  HIGH RISK    : {sum(1 for f in findings if 'HIGH' in f[0])}")
print(f"  MEDIUM RISK  : {sum(1 for f in findings if 'MEDIUM' in f[0])}")
print(f"  LOW RISK     : {sum(1 for f in findings if 'LOW' in f[0])}")
print()

for i, (risk, test, finding, recommendation) in enumerate(findings, 1):
    print(f"  FINDING #{i}  {risk}")
    print(f"  Test       : {test}")
    print(f"  Finding    : {finding}")
    print(f"  Action     : {recommendation}")
    print()

print("=" * 65)
print("  END OF AUDIT ANALYTICS REPORT")
print("  All charts saved as PNG files for inclusion in report")
print("  Next step: Compile findings into formal management report")
print("=" * 65)